### ISSUE TITLE
Assingment of network.f should be interpreted as Hz by default, such that nw2.f = nw1.f works properly

### ISSUE THREAD

**Issue by rk-exxec** [scikit-rf/scikit-rf#293] opened 2019-09-10 12:47 UTC
Hey, I ran into a problem with the following code:
```python
short_de_nw = rf.Network()
short_de_nw.z0 = short_nw.z0
short_de_nw.f = short_nw.f
short_de_nw.y = short_nw.y - open_nw.y
```

`short_nw `and `open_nw `are both Networks I loaded from s2p files
the first frequency for both is `45e6`, z0 is 50

However after the third line in the above code I would expect the first frequency of `short_de_nw `to be `45e6 `as well but I get `4.5e16`, how is that possible?
The same goes for all frequencies in that network, they get huge.

Is this a bug or am I using it wrong?

**Comment by JAnderson419** [comment] 2019-09-10 14:47
This is not technically a bug, just a very confusing feature.

Frequency data is stored in a Frequency object that includes an array of frequency data as well as a unit for the frequency. Network.f is shorthand for Network.frequency.f, which returns the frequency array. Likewise, setting Network.frequency.f creates a Frequency object and sets its frequency vector equal to the given argument. 

```
    @property
    def f(self):
        """
        the frequency vector for the network, in Hz.

        Returns
        --------
        f : :class:`numpy.ndarray`
                frequency vector in Hz

        See Also
        ---------
                frequency : frequency property that holds all frequency
                        information
        """
        return self.frequency.f

    @f.setter
    def f(self, f):
        tmpUnit = self.frequency.unit
        self.frequency = Frequency.from_f(f, unit=tmpUnit)
```
The problem you are seeing is because the default units of a Frequency object are ghz, which introduces an extra 1E9 factor. The workaround for this is to set ntwk2.frequency = ntwk1.frequency instead of ntwk2.f = ntwk1.f.


```
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import skrf as rf
>>> rf.Network("357_pcb_960978_um_pe_001_25.s3p")
3-Port Network: '357_pcb_960978_um_pe_001_25',  10.0-3000.0 MHz, 1601 pts, z0=[50.+0.j 50.+0.j 50.+0.j]
>>> ntwk = rf.Network("357_pcb_960978_um_pe_001_25.s3p")
>>> print(ntwk.frequency)
10.0-3000.0 MHz, 1601 pts
>>> print(ntwk.frequency.f)
[1.00000000e+07 2.14990000e+07 3.29980000e+07 ... 2.97252727e+09
 2.98626364e+09 3.00000000e+09]
>>> print(ntwk.frequency.unit)
MHz
>>> ntwk2 = rf.Network()
>>> ntwk2.f = ntwk.f
>>> print(ntwk2)
Warning: Network has improper 'z0' shape.
Warning: Network has improper 'z0' shape.
0-Port Network: '',  10000000.0-3000000000.0 GHz, 1601 pts, z0=(50+0j)
>>> ntwk2.frequency = ntwk.frequency
>>> print(ntwk2)
Warning: Network has improper 'z0' shape.
Warning: Network has improper 'z0' shape.
0-Port Network: '',  10.0-3000.0 MHz, 1601 pts, z0=(50+0j)
>>>
```

**Comment by rk-exxec** [comment] 2019-09-10 21:30
ah I see, thanks a lot!

**Comment by rk-exxec** [comment] 2019-09-10 21:32
If you don't mind me asking, is there a way to load data that i have in a dataframe into networks, I'm using s2p files for temporary storage as a workaround

**Comment by rk-exxec** [comment] 2019-09-11 20:05
Sorry to reopen this again, but the [docs](https://scikit-rf.readthedocs.io/en/latest/api/generated/skrf.frequency.Frequency.html#skrf.frequency.Frequency) state the following:

f | Frequency vector  in Hz
-- | --
f_scaled | Frequency vector in units of unit

Are the docs wrong here?

**Comment by rk-exxec** [comment] 2019-09-11 20:36
Yes its really odd, so I'll leave this issue open until it gets "fixed".

**Comment by jhillairet** [comment] 2020-07-26 15:18
Also a Duplicate of #91

**Comment by FranzForstmayr** [comment] 2022-10-19 22:43
Setting the frequency via the `f` property is deprecated, better assign a new frequency object.

```python
import skrf as rf
import numpy as np

net = rf.data.ring_slot
print(net)

net.frequency = rf.Frequency.from_f(np.arange(len(net)), 'Hz')
print(net)
```

**Closed by FranzForstmayr** 2022-10-19 22:43 UTC
Labels: Feature Request, Improvements
