### ISSUE TITLE
NISTMultilineTRL Discrepancy

### ISSUE THREAD

**Issue by JAnderson419** [scikit-rf/scikit-rf#600] opened 2022-01-18 13:56 UTC
Possible issue with NistMultilineTRL in calibration.py, reported to the scikit-rf google group by @ZiadHatab. NISTMultilineTRL inherits from EightTerm - is this potentially related to #572?

https://github.com/scikit-rf/scikit-rf/blob/2457bc4cb8ef2a188ecde89bfa373ca6b0ac775d/skrf/calibration/calibration.py#L2486

> Hi there!
> 
> I was testing your NIST multiline TRL (MultiCal) implementation using 150Ghz on-wafer measurements and I noticed that the result I get from your implementing differ from the one implemented I get from WinCal (https://www.formfactor.com/product/probes/calibration-tools/wincal-xe/)
> 
> I also programmed NIST MultiCal mTRL myself on python, and I get the same result as in WinCal, but different from the one in skrf. And to confirm this, I even tested it with my own original mTRL implementation, and its the same. All implemention agree with each other, but skrf differ?!
> 
>![image](https://user-images.githubusercontent.com/916439/149949956-ae932d10-6349-4bd4-ba6e-41cd1b36462b.png)
>
> You can check my github repo:
> https://github.com/ZiadHatab/multiline-trl-calibration
> You also find the on-wafer measurements i used. Also, attached is a screenshot comparing skrf calibration with the others.
> 
> best,
> Ziad

**Comment by jhillairet** [comment] 2022-01-18 14:10
Thanks for putting an issue, the email arrived in my spam box.

**Comment by Ttl** [comment] 2022-01-18 14:49
The mTRL code looks very good! Much clearer than what scikit-rf has currently. @ZiadHatab 

I didn't find the scikit-rf calibration code in the repository. I added it myself and got results much closer to other calibrations.

I think the main difference is that scikit-rf reference plane is at the end of the lines with non-zero thru while the other methods use center of thru reference. There also was a bug in previous versions related to non-zero thru case #533, that is fixed in the latest version. A1, A2, R1 and R2 term calculation method is slightly different, but I'm not sure if that's enough to explain the remaining difference.

![mtrl_s21](https://user-images.githubusercontent.com/544240/149958119-1eb6a5bd-b6e7-4052-92cf-1d78ec5c2400.png)
![mtrl_s11](https://user-images.githubusercontent.com/544240/149958127-0a35e843-6537-401b-a96e-917a4fb5f7c3.png)


My calibration code for reference in "example_2.py":
```
    line_lengths = [200e-6, 450e-6, 900e-6, 1800e-6]
    offset = line_lengths[0]
    line_lengths = [i - offset for i in line_lengths]
...
    measured = [L1, SHORT, L2, L3, L4]
    cal = rf.NISTMultilineTRL(
        measured = measured,
        Grefls = [-1],
        l = line_lengths,
        er_est = 5,
        switch_terms = (gamma_f, gamma_r)
    )
```

**Comment by ZiadHatab** [comment] 2022-01-18 15:24
@Ttl 
Thanks for looking into it. They do look alike, but if you include the other lines in the calibration (L5, L6), then the difference become much larger. I included a modified script of my example_2, where I included also skrf in it. You will get the same result that you got if comment L5 and L6.

Regarding your idea that skrf shifts the plane of calibration to the end of the fixtures. I dont think that is the case, as the parameter 'ref_plane=0', which by default take the first line as thru (remember in mTRL, we take line differences. i.e., any common offset will just be subtracted). Also, in the documentation it says:

>        ref_plane : float or list of float
>            Reference plane shift after the calibration.
>            Negative length is towards the VNA. Units are in meters.
>
>            Different shifts can be given to different ports by giving a two element list.
>            First element is shift of port 1 and second is shift of port 2.

Also, if you look in skrf's code, they set the first line as thru. That means after calibration it will be in the middle.

```python
        # The first line is thru
        self.l = [i - self.l[0] for i in self.l]
```

So, my speculation will be on how the common line is selected. The code in skrf doesn't make much sense to me. It seems to me some 'line pairs' are ignored according to this for-loop. I think the issue is with the second loop with the k . shouldn't both loops run through all lines to create all 'line pairs' and then decide which group is the best (minimum phi)?

```python
        for m in range(fpoints):
            min_phi_eff = pi*npy.ones(lines)
            #Find the best common line to use
            for n in range(lines):
                for k in range(n-1):
                    dl = l[k] - l[n]
                    pd = abs(exp(-gamma_est*dl) - exp(gamma_est*dl))/2
                    if -1 <= pd <= 1:
                        phi_eff = npy.arcsin( pd )
                    else:
                        phi_eff = 0
                    min_phi_eff[n] = min(min_phi_eff[n], phi_eff)
            #Common line is selected to be one with the largest phase difference
            line_c[m] = npy.argmax(min_phi_eff)
```

[mTRL_.zip](https://github.com/scikit-rf/scikit-rf/files/7890078/mTRL_.zip)

**Comment by ZiadHatab** [comment] 2022-01-18 16:10
You are right about the reference plane. I didn't see the try-except statement, where the reference plane is set.

Back to the issue. Did you try including L5 and L6 in the calibration?

```python
    lines = [L1, L2, L3, L4
             , L5, L6
             ]
    line_lengths = [200e-6, 450e-6, 900e-6, 1800e-6
                    , 3500e-6, 5250e-6
                    ]
```
Also, when I check S22, the discrepancy is much more apparent.

**Comment by denzchoe** [comment] 2022-01-19 02:30
@ZiadHatab, Back in 2017, I did a comparison between WinCal mTRL, and skrf NISTmTRL on my Wafer measurements; I saw the discrepancy like you did. So I did a little digging; and realised that WinCal mTRL shifts the ref plane back to the probe tips. Whereas skrf NISTmTRL retain ref plane at the half of the thru cal standard. 

When I shifted the ref plane to equal positions for either one of them (via WinCal menu or via skrf later); I got the same results (resonance dips, and insertion losses) occurring at similar frequencies. It was a painful learning experience.

I think you can do a quick check your S21_deg and see whether they are at the same electrical length for the same DUT. It should clearly show which one is shifted.

**Comment by ZiadHatab** [comment] 2022-01-19 14:27
@denzchoe 
Thanks for the info. I already double checked with the cal plane. It is not the issue. I compared the results when both cal planes are the same. 

@Ttl 
Since the problem is mainly in S11 and S22. I checked the skrf code again. In the step where the parameter Arr is computed, you guys use the equation from the paper "Multiline TRL Revealed":

```python
                    Arr = (S_r11 - B1)/(1 - S_r11*CoA1)* \
                            (1 - S_r22*CoA2)/(S_r22 - B2)
```

This is actually incorrect, it should be:

```python
                    Arr = (S_r11 - B1)/(1 - S_r11*CoA1)* \
                            (1 + S_r22*CoA2)/(S_r22 + B2)
```

This is a typo in the original paper. Although, i'm not sure if it is really a typo or intentionally, because they seem to have a lot of typos in their equations (check the comments in my script MultiCal.py).

I'm not sure if this is the cause of the issue. But it was something I noticed.

**Comment by ZiadHatab** [comment] 2022-01-19 14:57
@Ttl 
Ok, a quick update. I forgot that you guys used another reference for the implementation:

> Yau “On the metrology of nanoscale Silicon transistors above 100 GHz” Ph.D. dissertation, Dept. Elec. Eng. and Comp. Eng., University of Toronto, Toronto, Canada, 2011.

In the reference above, the author flipped the right error-box to re-use the equations from the left error-box. So, the equation for Arr in skrf is correct (but still wrong in the original paper from NIST. They didn't flip the right error-box).

Regardless, I think I found the culprit. It is the equation where you computed A1A2. Here you guys used the equation from NIST's paper, which is wrong in your case, since your right error-box is flipped. You should use the equation in the reference you guys listed.

So, instead of this (NIST's paper):
![image](https://user-images.githubusercontent.com/46247580/150155096-136895e5-338e-487e-a4a5-ca7f170f7022.png)
```python
                Ap = B1*B2 - B1*S_thru[1,1] - B2*S_thru[0,0] + linalg.det(S_thru)
                Ap = -Ap/(1 - CoA1*S_thru[0,0] - CoA2*S_thru[1,1] + CoA1*CoA2*linalg.det(S_thru))
```

It should be (above ref.):
![image](https://user-images.githubusercontent.com/46247580/150155287-7e794d4c-824b-442c-b207-4d90add3f598.png)
```python
                Ap = -B1*B2 - B1*S_thru[1,1] + B2*S_thru[0,0] + linalg.det(S_thru)
                Ap = -Ap/(1 - CoA1*S_thru[0,0] + CoA2*S_thru[1,1] - CoA1*CoA2*linalg.det(S_thru))
```

**Comment by Ttl** [comment] 2022-01-19 15:22
I made a new PR to fix a problem with Vc and Vb matrix calculation. Now with your script skrf and multical results agree much better:

![mtrl2_s11](https://user-images.githubusercontent.com/544240/150160096-6cc327e0-63fe-4164-acf5-80a0fdab5dc9.png)

I tested also your proposed change but it seems to generate clearly incorrect calibration result.

**Comment by ZiadHatab** [comment] 2022-01-19 15:24
Cool!

Do you also get a similar agreement in S22?

**Comment by Ttl** [comment] 2022-01-19 15:31
It almost agrees:

![mtrl2_s22](https://user-images.githubusercontent.com/544240/150161901-5c8cc542-33a9-4444-a1c0-14a82f4f08bf.png)

There's a slight glitch around 100 GHz and skrf result seems worse.

**Comment by ZiadHatab** [comment] 2022-01-19 15:33
Nice!

The glitch is most likely from the common line. Are you using the skrf common line function?

**Comment by Ttl** [comment] 2022-01-19 16:04
It turns out that I missed one wrong conjugation in the matrix calculations. Now S22 agrees perfectly. Thanks for the bug report, this turned out to be very useful.

![mtrl3_s22](https://user-images.githubusercontent.com/544240/150168458-1184d53d-d44d-4f4f-be35-ea2840fe9160.png)

**Comment by ZiadHatab** [comment] 2022-01-19 16:07
cool, they look identical.

glad I was able to help.

**Comment by jhillairet** [comment] 2022-01-19 16:18
> It turns out that I missed one wrong conjugation in the matrix calculations. Now S22 agrees perfectly. Thanks for the bug report, this turned out to be very useful.

Thanks @Ttl  for this fix.

By the way, is it related to #572?

**Comment by Ttl** [comment] 2022-01-19 16:24
No relation to #572. That one seemed to be just a problem with incorrect switch terms given to the calibration.

**Comment by jhillairet** [comment] 2022-01-19 16:30
ok, thanks. Let me know when you think your PR can be safely merged.

**Comment by Ttl** [comment] 2022-01-19 16:57
It should be good to merge but might as well keep it open for a while in case anyone has comments.

**Closed** 2022-01-22 10:11 UTC
Labels: Bug, Calibration
