### ISSUE TITLE
https://scikit-rf.readthedocs.io site is broken 

### ISSUE THREAD

**Issue by vishak-venkatraman** [scikit-rf/scikit-rf#774] opened 2022-10-19 14:42 UTC
<img width="769" alt="image" src="https://user-images.githubusercontent.com/67716193/196723271-90e5c51e-8ed2-4aaa-90fe-e11fb1c603c7.png">

**Comment by FranzForstmayr** [comment] 2022-10-19 14:58
I'll check later

**Comment by FranzForstmayr** [comment] 2022-10-19 19:26
Hmm, I'm unable to reproduce locally...
And it's strange that no build error is shown:
https://readthedocs.org/api/v2/build/18384426.txt

**Comment by FranzForstmayr** [comment] 2022-10-19 21:03
Opened a support ticket at readthedocs.org, hope I'll get an answer.

**Comment by FranzForstmayr** [comment] 2022-10-20 10:28
Fixed with #775

**Closed by FranzForstmayr** 2022-10-20 10:28 UTC

**Comment by arsenovic** [comment] 2022-10-20 11:56
fyi the calls the rf.styley() are causing errors in the docs still...

**Comment by FranzForstmayr** [comment] 2022-10-20 12:02
Should be fixed with the next build too
