### ISSUE TITLE
NF Analysis

### ISSUE THREAD

**Issue by ghost** [scikit-rf/scikit-rf#539] opened 2021-10-14 14:17 UTC
In Scikit rf, NF for two-port active networks that have noisy parameters accompany with scattering parameters works fine. noisy parameters for passive networks is depended on its scattering parameters and the required formula has not been developed for that. Therefore, Scikit rf will not support the NF calculation for passive networks . The noise parameters of the passive networks are depended on its scattering parameters as reported here:
A. S. Morris and R. J. Trew, "Simple noise analysis applied to power combiners," IEEE International Digest on Microwave Symposium, 1990, pp. 1273-1275 vol.3, doi: 10.1109/MWSYM.1990.99811. 
It also seems the NF only works for cascading of two port networks and it has not been extended to cascading of multi-port networks. Circuit method for cascading multiple-port networks will remove the noisy parameters of each internal network instead of combining as one noisy parameters for the overall network.

**Comment by jhillairet** [comment] 2021-10-14 16:27
Indeed, but I think it's a duplicate of your previous issue #538, isn't ?

**Closed as completed** 2021-10-20 18:43 UTC
