### ISSUE TITLE
Issue with TRL and determine_reflect

### ISSUE THREAD

**Issue by eendebakpt** [scikit-rf/scikit-rf#865] opened 2023-03-28 10:49 UTC
The TRL calibration procedure is giving some unexpected (incorrect?) results. I tracking it down to the following minimal example.
I define a perfect thru, reflect and line and then run `determine_reflect`. I would expect it to return a reasonable estimate for the reflect, but instead I get `NaN` values.
```
import skrf
from skrf.media import CPW, Coaxial
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from skrf.calibration import determine_reflect
np.set_printoptions(threshold=8)

# define medium
freq = skrf.F(.5,.7,801, unit='GHz')
att_db_per_meter = 3.0
medium=Coaxial.from_attenuation_VF(freq, att=att_db_per_meter, VF=.69)

# define measurements
thru = medium.line(0, 'm')
line=medium.line(0.12, 'm')
short = medium.short()
short2port = skrf.two_port_reflect(short, short)
    
# check our frequency is in the valid range for TRL
w = np.rad2deg(np.imag( medium.electrical_length(.12)))
print(f'TRL bandwidth {w[0], w[-1]}')


rr=determine_reflect(thru, short2port, line, short2port, line, return_all=True)

for r in rr:
    print(r.s)
    
# Do not give any hints
rr=determine_reflect(thru, short2port, line, return_all=True)
for r in rr:
    print(r.s)
````

**Comment by Ttl** [comment] 2023-03-29 13:10
The issue is caused by division by zero when thru and line are both perfectly matched. You can work around it in this case by adding a tiny amount of mismatch:

```python
thru.s[:,0,0] += 1e-7
thru.s[:,1,1] += 1e-7
```

**Comment by eendebakpt** [comment] 2023-03-29 20:15
@Ttl Adding the small mismatch indeed allows the run the algorithm with good results. Often when near singularities algorithms become a bit unstable, but that does not appear to be the case here. I tested with 
```
thru.s[:,0,0] += 1e-7
thru.s[:,1,1] += 1e-7
thru.add_noise_polar(1e-7, 1e-7)
```
and that gives good results as well.

Do you have any insight why the division by zero occurs for matched thru and line? I seems to me it should be an easy case, and I am a bit wary of algorithms that have issues with easy cases.

One division by zero I could track down and resolve, see https://github.com/scikit-rf/scikit-rf/commit/cd4c26c04c44d159737a1614344db1410baa25fe. Another division by zero is occuring because `a` in the section https://github.com/scikit-rf/scikit-rf/blob/30a1d9cee3a97f02f5401a44881b3dc70c32f964/skrf/calibration/calibration.py#L5753-L5763 has zero elements. The core there seems to be solving a quadratic equation, but I cannot figure out exactly which one.

For the elements where `a= tt[:, 1, 0]` is zero, the equation reduces to a linear equation and we could modify the code to
```
    a = tt[:,1,0]
    b = tt[:,1,1]-tt[:,0,0]
    c = -tt[:,0,1]

    sqrt_D = sqrt(b*b-4*a*c)
    a_zero_idx = np.abs(a)<1e-16
    a_nonzero_idx = a_zero_idx==False

    sol1 = np.empty_like(a)
    sol2 = np.empty_like(a)    
    sol1[a_nonzero_idx] = (-b[a_nonzero_idx]-sqrt_D[a_nonzero_idx])/(2*a[a_nonzero_idx])
    sol2[a_nonzero_idx] = (-b[a_nonzero_idx]+sqrt_D[a_nonzero_idx])/(2*a[a_nonzero_idx])
    sol1[a_zero_idx] = sol2[a_zero_idx] = -c[a_zero_idx]/b[a_zero_idx]
```
That works, but there are more equations in `determine_reflect` that have to be modified in a simular fashion, and it would be good to have some context before I work that out further.

**Comment by Ttl** [comment] 2023-03-29 20:39
The algorithm is described in the original TRL paper (http://jsa.ece.illinois.edu/ece451_old/appnotes/trl_paper.pdf). In the perfectly matched case `sol1`and `sol2` are zero and infinity. Since the derivation uses the solutions in further steps it's dividing by zero or multiplying by infinity in practically all calculations.

**Comment by jhillairet** [comment] 2023-03-30 19:48
@eendebakpt can we close this issue following #868?

**Closed** 2023-04-19 20:57 UTC
Labels: Calibration
